version: 2.1

workflows:
  ninja-testing:
    jobs:
      - check-python
      - test-ninja-class-all:
          requires:
            - check-python
      - test-ninja-class-one-by-one:
          requires:
            - check-python

jobs:
  check-python:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Check Python Version
          command: python --version
      - run:
          name: Update pip
          command: /home/circleci/.pyenv/versions/3.8.13/bin/python3.8 -m pip install --upgrade pip

  test-ninja-class-all:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Behave
          command: pip install behave
      - run:
          name: Test All Ninja Test Case
          command: python main.py all
      - store_test_results:
          path: /tmp/test-results

  test-ninja-class-one-by-one:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Behave
          command: pip install behave
      - run:
          name: Test Ninja Ignore Test Case
          command: python main.py ignore
      - run:
          name: Test Ninja Fight Test Cases
          command: python main.py fight
      - run:
          name: Test Ninja Run Test Cases
          command: python main.py run
      - store_test_results:
          path: /tmp/test-results
     
