version: 2.1

workflows:
  ninja-testing:
    jobs:
      - check-python
      - test-ninja-encounter:
          requires:
            - check-python

jobs:
  check-python:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Check Python Version
          command: python --version
      - run:
          name: Update pip
          command: /home/circleci/.pyenv/versions/3.8.13/bin/python3.8 -m pip install --upgrade pip

  test-ninja-encounter:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Behave
          command: pip install behave
      - run:
          name: Ninja Encounters
          command: python main.py encounter
