version: 2.1

workflows:
  ninja-testing:
    jobs:
      - check-python
      - test-ninja-class:
          requires:
            - check-python

jobs:
  check-python:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Check Python Version
          command: python --version
      - run:
          name: Update pip
          command: /home/circleci/.pyenv/versions/3.8.13/bin/python3.8 -m pip install --upgrade pip

  test-ninja-class:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Behave
          command: pip install behave
      - run:
          name: Test Ninja Ignore Test Case
          command: python main.py ignore
      - run:
          name: Test Ninja Fight Test Cases
          command: python main.py fight
      - run:
          name: Test Ninja Run Test Cases
          command: python main.py run
     
